appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: V42n5XJozwcx++irdA7e+UQtgae7Y5fqeWmsL4Ah5tj5NKuXPmmTn/Vni4q/yfr+PVPzCmSnNR3VUAocrbt6+6Jz9jQxLSaKVinDEzACKeN3Z+v7+vq4Ov79tQjLzsHFjo3qgEg4YbsVI4AmG9y09uDkUDCmvEljAXXI7Cgzn4Xb6312dCz3XIjpmC/9thVStqnoo5N1hogrzwMhu5NJW8SGrwUREqW12olphexgahJBu8qeF+eKJkJ+iLtTG1hlxA2Gy8l0h81/emLJFdA7LAA7bAekaVY2IvfPZkFNS9yk01WUS8F5IZZgUp4mhW4GjXCGqlVu7d1qBUxxd1d2t2N1cG4i70d7UVhiUp7keL7UaJWMwvsWbq6NJ/YdkXMiCzDgaSxjrivOtsMmSlSR/uzcwID1uWZNAsO1lC4vlMPiMG1JfG6tM8+J+w3k1ITuLue1v5HT1cLtsnlvEzNmIzpG/ZVfO3IQKaThKny8nOzXC+Z8Q+LGP4KxpjxhUDWl6TOH7pn7ciKQI8Ysm1W83qpqALhN4t/p7x0q1+O1ZY2s3+8bCBD8V/6Fyx9MQpAHIgyiOuoZGoE50i9+l2Jc/QVt7TafeU9oQxJCTDsnuTV/uvJbvKemfpeGVD/1blNxHUVJzctuzbaZXdVBue5ieqntdnTpo8rou8f0iKd6lhs=}
